domain_path: /home/notblackmagic/Documents/Vitis/KR260/CortexR5/export/CortexR5/sw/freertos_psu_cortexr5_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
