set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_2_0/kr260_proc_sys_reset_2_0.xdc rfile:../../../TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_2_0/kr260_proc_sys_reset_2_0.xdc id:1 order:EARLY scoped_inst:kr260_i/proc_sys_reset_3/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_1_0/kr260_proc_sys_reset_1_0.xdc rfile:../../../TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_1_0/kr260_proc_sys_reset_1_0.xdc id:2 order:EARLY scoped_inst:kr260_i/proc_sys_reset_2/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_0_0/kr260_proc_sys_reset_0_0.xdc rfile:../../../TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_0_0/kr260_proc_sys_reset_0_0.xdc id:3 order:EARLY scoped_inst:kr260_i/proc_sys_reset_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0.xdc rfile:../../../TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0.xdc id:4 order:EARLY scoped_inst:kr260_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.srcs/constrs_1/new/fan_pinout.xdc rfile:../../../TestPixhawk.srcs/constrs_1/new/fan_pinout.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.srcs/constrs_1/new/pixhawk_pinout.xdc rfile:../../../TestPixhawk.srcs/constrs_1/new/pixhawk_pinout.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.srcs/constrs_1/new/rpi_pinout.xdc rfile:../../../TestPixhawk.srcs/constrs_1/new/rpi_pinout.xdc id:7} [current_design]
current_instance kr260_i/proc_sys_reset_3/U0
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_i/proc_sys_reset_2/U0
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_i/proc_sys_reset_1/U0
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
set_property src_info {type:XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {fan_en_b}]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {IMU0_I2C_scl_io}]
set_property src_info {type:XDC file:6 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {IMU0_I2C_sda_io}]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {GPIO0_tri_io[0]}]
set_property src_info {type:XDC file:6 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports {GPIO0_tri_io[1]}]
set_property src_info {type:XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {IMU1_I2C_scl_io}]
set_property src_info {type:XDC file:6 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {IMU1_I2C_sda_io}]
set_property src_info {type:XDC file:6 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {GPIO0_tri_io[2]}]
set_property src_info {type:XDC file:6 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports {GPIO0_tri_io[3]}]
set_property src_info {type:XDC file:6 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports {GPS0_UART_txd}]
set_property src_info {type:XDC file:6 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports {GPS0_UART_rxd}]
set_property src_info {type:XDC file:6 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {GPS0_I2C_scl_io}]
set_property src_info {type:XDC file:6 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {GPS0_I2C_sda_io}]
set_property src_info {type:XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {GPIO0_tri_io[4]}]
set_property src_info {type:XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {GPIO0_tri_io[5]}]
set_property src_info {type:XDC file:6 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {GPIO0_tri_io[6]}]
set_property src_info {type:XDC file:6 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports {GPIO0_tri_io[7]}]
set_property src_info {type:XDC file:6 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12 [get_ports {RC_SBUS0_txd}]
set_property src_info {type:XDC file:6 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {RC_SBUS0_rxd}]
set_property src_info {type:XDC file:6 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10 [get_ports {ENC_CAP0}]
set_property src_info {type:XDC file:6 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH10 [get_ports {GPIO0_tri_io[8]}]
set_property src_info {type:XDC file:6 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11 [get_ports {RC_PWM0}]
set_property src_info {type:XDC file:6 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11 [get_ports {RC_PWM1}]
set_property src_info {type:XDC file:6 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12 [get_ports {RC_PWM2}]
set_property src_info {type:XDC file:6 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11 [get_ports {RC_PWM3}]
set_property src_info {type:XDC file:6 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC12 [get_ports {TELEM0_txd}]
set_property src_info {type:XDC file:6 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports {TELEM0_rxd}]
set_property src_info {type:XDC file:6 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10 [get_ports {GPIO0_tri_io[9]}]
set_property src_info {type:XDC file:6 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports {GPIO0_tri_io[10]}]
set_property src_info {type:XDC file:6 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports {TELEM1_txd}]
set_property src_info {type:XDC file:6 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10 [get_ports {TELEM1_rxd}]
set_property src_info {type:XDC file:6 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports {GPIO0_tri_io[11]}]
set_property src_info {type:XDC file:6 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports {GPIO0_tri_io[12]}]
set_property src_info {type:XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {GPIO0_tri_io[13]}]
set_property src_info {type:XDC file:7 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {GPIO0_tri_io[14]}]
set_property src_info {type:XDC file:7 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports {GPIO0_tri_io[15]}]
set_property src_info {type:XDC file:7 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports {GPIO0_tri_io[16]}]
set_property src_info {type:XDC file:7 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {GPIO0_tri_io[17]}]
set_property src_info {type:XDC file:7 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {GPIO0_tri_io[18]}]
set_property src_info {type:XDC file:7 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {GPIO0_tri_io[19]}]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG13 [get_ports {GPIO0_tri_io[20]}]
set_property src_info {type:XDC file:7 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {GPIO0_tri_io[21]}]
set_property src_info {type:XDC file:7 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {GPIO0_tri_io[22]}]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {GPIO0_tri_io[23]}]
set_property src_info {type:XDC file:7 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {GPIO0_tri_io[24]}]
set_property src_info {type:XDC file:7 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports {GPIO0_tri_io[25]}]
set_property src_info {type:XDC file:7 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {GPIO0_tri_io[26]}]
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {GPIO0_tri_io[27]}]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13 [get_ports {GPIO0_tri_io[28]}]
set_property src_info {type:XDC file:7 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {GPIO0_tri_io[29]}]
set_property src_info {type:XDC file:7 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {GPIO0_tri_io[30]}]
set_property src_info {type:XDC file:7 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports {GPIO0_tri_io[31]}]
set_property src_info {type:XDC file:7 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE14 [get_ports {I2C0_scl_io}]
set_property src_info {type:XDC file:7 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {I2C0_sda_io}]
set_property src_info {type:XDC file:7 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {UART0_txd}]
set_property src_info {type:XDC file:7 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {UART0_rxd}]
