# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fan_pinout.xdc

# XDC: new/pixhawk_pinout.xdc

# XDC: new/rpi_pinout.xdc

# Block Designs: bd/kr260/kr260.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260 || ORIG_REF_NAME==kr260} -quiet] -quiet

# IP: bd/kr260/ip/kr260_zynq_ultra_ps_e_0_0/kr260_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kr260_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_clk_wiz_0_0 || ORIG_REF_NAME==kr260_clk_wiz_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_proc_sys_reset_0_0/kr260_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_0_0 || ORIG_REF_NAME==kr260_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_proc_sys_reset_1_0/kr260_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_1_0 || ORIG_REF_NAME==kr260_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_proc_sys_reset_2_0/kr260_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_2_0 || ORIG_REF_NAME==kr260_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_intc_0_0/kr260_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_intc_0_0 || ORIG_REF_NAME==kr260_axi_intc_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_xbar_0/kr260_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_xbar_0 || ORIG_REF_NAME==kr260_xbar_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_ps8_0_axi_periph_0/kr260_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_ps8_0_axi_periph_0 || ORIG_REF_NAME==kr260_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_xlslice_0_0/kr260_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_xlslice_0_0 || ORIG_REF_NAME==kr260_xlslice_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_xlconcat_0_0/kr260_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_xlconcat_0_0 || ORIG_REF_NAME==kr260_xlconcat_0_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_iic_0_1/kr260_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_iic_0_1 || ORIG_REF_NAME==kr260_axi_iic_0_1} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_iic_1_0/kr260_axi_iic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_iic_1_0 || ORIG_REF_NAME==kr260_axi_iic_1_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_uartlite_0_1/kr260_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_0_1 || ORIG_REF_NAME==kr260_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_iic_2_0/kr260_axi_iic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_iic_2_0 || ORIG_REF_NAME==kr260_axi_iic_2_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_uartlite_1_0/kr260_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_1_0 || ORIG_REF_NAME==kr260_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_gpio_0_1/kr260_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_gpio_0_1 || ORIG_REF_NAME==kr260_axi_gpio_0_1} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_uartlite_2_0/kr260_axi_uartlite_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_2_0 || ORIG_REF_NAME==kr260_axi_uartlite_2_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_uartlite_3_0/kr260_axi_uartlite_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_3_0 || ORIG_REF_NAME==kr260_axi_uartlite_3_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_iic_3_0/kr260_axi_iic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_iic_3_0 || ORIG_REF_NAME==kr260_axi_iic_3_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_timer_0_1/kr260_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_timer_0_1 || ORIG_REF_NAME==kr260_axi_timer_0_1} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_timer_0_2/kr260_axi_timer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_timer_0_2 || ORIG_REF_NAME==kr260_axi_timer_0_2} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_timer_2_1/kr260_axi_timer_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_timer_2_1 || ORIG_REF_NAME==kr260_axi_timer_2_1} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_timer_2_2/kr260_axi_timer_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_timer_2_2 || ORIG_REF_NAME==kr260_axi_timer_2_2} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_timer_4_0/kr260_axi_timer_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_timer_4_0 || ORIG_REF_NAME==kr260_axi_timer_4_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_axi_uartlite_4_0/kr260_axi_uartlite_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_4_0 || ORIG_REF_NAME==kr260_axi_uartlite_4_0} -quiet] -quiet

# IP: bd/kr260/ip/kr260_auto_pc_0/kr260_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_auto_pc_0 || ORIG_REF_NAME==kr260_auto_pc_0} -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_zynq_ultra_ps_e_0_0/kr260_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_zynq_ultra_ps_e_0_0/kr260_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kr260_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_clk_wiz_0_0 || ORIG_REF_NAME==kr260_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_clk_wiz_0_0 || ORIG_REF_NAME==kr260_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_0_0/kr260_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_0_0 || ORIG_REF_NAME==kr260_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_0_0/kr260_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_0_0 || ORIG_REF_NAME==kr260_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_1_0/kr260_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_1_0 || ORIG_REF_NAME==kr260_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_1_0/kr260_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_1_0 || ORIG_REF_NAME==kr260_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_2_0/kr260_proc_sys_reset_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_2_0 || ORIG_REF_NAME==kr260_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_proc_sys_reset_2_0/kr260_proc_sys_reset_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_proc_sys_reset_2_0 || ORIG_REF_NAME==kr260_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_intc_0_0/kr260_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_intc_0_0 || ORIG_REF_NAME==kr260_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_intc_0_0/kr260_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_intc_0_0 || ORIG_REF_NAME==kr260_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_intc_0_0/kr260_axi_intc_0_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_0_1/kr260_axi_iic_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_iic_0_1 || ORIG_REF_NAME==kr260_axi_iic_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_0_1/kr260_axi_iic_0_1_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_1_0/kr260_axi_iic_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_iic_1_0 || ORIG_REF_NAME==kr260_axi_iic_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_1_0/kr260_axi_iic_1_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_0_1/kr260_axi_uartlite_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_0_1 || ORIG_REF_NAME==kr260_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_0_1/kr260_axi_uartlite_0_1_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_0_1/kr260_axi_uartlite_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_0_1 || ORIG_REF_NAME==kr260_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_2_0/kr260_axi_iic_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_iic_2_0 || ORIG_REF_NAME==kr260_axi_iic_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_2_0/kr260_axi_iic_2_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_1_0/kr260_axi_uartlite_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_1_0 || ORIG_REF_NAME==kr260_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_1_0/kr260_axi_uartlite_1_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_1_0/kr260_axi_uartlite_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_1_0 || ORIG_REF_NAME==kr260_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_gpio_0_1/kr260_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_gpio_0_1 || ORIG_REF_NAME==kr260_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_gpio_0_1/kr260_axi_gpio_0_1_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_gpio_0_1/kr260_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_gpio_0_1 || ORIG_REF_NAME==kr260_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_2_0/kr260_axi_uartlite_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_2_0 || ORIG_REF_NAME==kr260_axi_uartlite_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_2_0/kr260_axi_uartlite_2_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_2_0/kr260_axi_uartlite_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_2_0 || ORIG_REF_NAME==kr260_axi_uartlite_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_3_0/kr260_axi_uartlite_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_3_0 || ORIG_REF_NAME==kr260_axi_uartlite_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_3_0/kr260_axi_uartlite_3_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_3_0/kr260_axi_uartlite_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_3_0 || ORIG_REF_NAME==kr260_axi_uartlite_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_3_0/kr260_axi_iic_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_iic_3_0 || ORIG_REF_NAME==kr260_axi_iic_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_iic_3_0/kr260_axi_iic_3_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_0_1/kr260_axi_timer_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_timer_0_1 || ORIG_REF_NAME==kr260_axi_timer_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_0_1/kr260_axi_timer_0_1_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_0_2/kr260_axi_timer_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_timer_0_2 || ORIG_REF_NAME==kr260_axi_timer_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_0_2/kr260_axi_timer_0_2_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_2_1/kr260_axi_timer_2_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_timer_2_1 || ORIG_REF_NAME==kr260_axi_timer_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_2_1/kr260_axi_timer_2_1_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_2_2/kr260_axi_timer_2_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_timer_2_2 || ORIG_REF_NAME==kr260_axi_timer_2_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_2_2/kr260_axi_timer_2_2_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_4_0/kr260_axi_timer_4_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_timer_4_0 || ORIG_REF_NAME==kr260_axi_timer_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_timer_4_0/kr260_axi_timer_4_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_4_0/kr260_axi_uartlite_4_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_4_0 || ORIG_REF_NAME==kr260_axi_uartlite_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_4_0/kr260_axi_uartlite_4_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_axi_uartlite_4_0/kr260_axi_uartlite_4_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kr260_axi_uartlite_4_0 || ORIG_REF_NAME==kr260_axi_uartlite_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/ip/kr260_auto_pc_0/kr260_auto_pc_0_ooc.xdc

# XDC: /home/notblackmagic/Documents/Vivado/TestPixhawk/TestPixhawk.gen/sources_1/bd/kr260/kr260_ooc.xdc
