#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Script generated by Vivado on Sun May 26 10:41:28 WEST 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : kr260.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : kr260.sh
#                kr260.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                kr260.sh [-reset_run]
#                kr260.sh [-reset_log]
#                kr260.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'kr260.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_16 -libname zynq_ultra_ps_e_vip_v1_0_16 -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname axi_lite_ipif_v3_0_4 -libname axi_intc_v4_1_18 -libname generic_baseblocks_v2_1_1 -libname axi_register_slice_v2_1_30 -libname fifo_generator_v13_2_9 -libname axi_data_fifo_v2_1_29 -libname axi_crossbar_v2_1_31 -libname xlslice_v1_0_3 -libname xlconcat_v2_1_5 -libname lib_pkg_v1_0_3 -libname lib_srl_fifo_v1_0_3 -libname axi_uartlite_v2_0_34 -libname interrupt_control_v3_1_5 -libname axi_iic_v2_1_6 -libname axi_gpio_v2_0_32 -libname axi_timer_v2_0_32 -libname axi_protocol_converter_v2_1_30 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_16 zynq_ultra_ps_e_vip_v1_0_16 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 axi_lite_ipif_v3_0_4 axi_intc_v4_1_18 generic_baseblocks_v2_1_1 axi_register_slice_v2_1_30 fifo_generator_v13_2_9 axi_data_fifo_v2_1_29 axi_crossbar_v2_1_31 xlslice_v1_0_3 xlconcat_v2_1_5 lib_pkg_v1_0_3 lib_srl_fifo_v1_0_3 axi_uartlite_v2_0_34 interrupt_control_v3_1_5 axi_iic_v2_1_6 axi_gpio_v2_0_32 axi_timer_v2_0_32 axi_protocol_converter_v2_1_30)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "kr260.sh - Script generated by export_simulation (Vivado v2023.2.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./kr260.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_16 $xmvlog_opts -sv +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/fd36/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work zynq_ultra_ps_e_vip_v1_0_16 $xmvlog_opts -sv +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/ip/kr260_zynq_ultra_ps_e_0_0/sim/kr260_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  "../../../bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/kr260/ip/kr260_clk_wiz_0_0/kr260_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_proc_sys_reset_0_0/sim/kr260_proc_sys_reset_0_0.vhd" \
  "../../../bd/kr260/ip/kr260_proc_sys_reset_1_0/sim/kr260_proc_sys_reset_1_0.vhd" \
  "../../../bd/kr260/ip/kr260_proc_sys_reset_2_0/sim/kr260_proc_sys_reset_2_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_intc_v4_1_18 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/d764/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_axi_intc_0_0/sim/kr260_axi_intc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_30 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/85f1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_29 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/7964/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_31 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ba70/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/ip/kr260_xbar_0/sim/kr260_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlslice_v1_0_3 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/217a/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/ip/kr260_xlslice_0_0/sim/kr260_xlslice_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/ip/kr260_xlconcat_0_0/sim/kr260_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uartlite_v2_0_34 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/302d/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_axi_uartlite_0_0/sim/kr260_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_iic_v2_1_6 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/9ead/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_axi_iic_0_0/sim/kr260_axi_iic_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_32 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/32ee/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_axi_gpio_0_0/sim/kr260_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_timer_v2_0_32 -V93 $xmvhdl_opts \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/6551/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/kr260/ip/kr260_axi_timer_0_0/sim/kr260_axi_timer_0_0.vhd" \
  "../../../bd/kr260/ip/kr260_axi_timer_1_0/sim/kr260_axi_timer_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/sim/kr260.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_30 $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../TestIO.gen/sources_1/bd/kr260/ipshared/3956/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/ec67/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/f261/hdl" +incdir+"../../../../TestIO.gen/sources_1/bd/kr260/ipshared/c2c6" +incdir+"/tools/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/kr260/ip/kr260_auto_pc_0/sim/kr260_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.kr260 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.kr260 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/notblackmagic/Documents/Vivado/TestIO/TestIO.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log kr260_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./kr260.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: kr260.sh [-help]\n\
Usage: kr260.sh [-step]\n\
Usage: kr260.sh [-lib_map_path]\n\
Usage: kr260.sh [-reset_run]\n\
Usage: kr260.sh [-reset_log]\n\
Usage: kr260.sh [-keep_index]\n\
Usage: kr260.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
